from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def read_source_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines()


def ignored_prefix_offset(map_data: dict[str, Any]) -> int:
    source_file = map_data.get("source_file", {})
    ignored_lines = source_file.get("ignored_prefix_lines", [])
    return len(ignored_lines)


def normalized_span(scene: dict[str, Any], map_data: dict[str, Any], total_lines: int) -> tuple[int, int]:
    offset = ignored_prefix_offset(map_data)
    start = scene["source_line_start"] - offset
    end = scene["source_line_end"] - offset
    if start < 1 or end < start or end > total_lines:
        raise ValueError(
            f"{scene['scene_id']} span {scene['source_line_start']}-{scene['source_line_end']} "
            f"normalizes to invalid range {start}-{end}."
        )
    return start, end


def scene_excerpt_text(scene: dict[str, Any], map_data: dict[str, Any], source_lines: list[str]) -> str:
    start, end = normalized_span(scene, map_data, total_lines=len(source_lines))
    excerpt = "\n".join(source_lines[start - 1:end])
    return (
        f"# {scene['scene_id']} Scene Excerpt\n\n"
        f"- Source file: `source/screenplay/closing_price.fountain`\n"
        f"- Source lines: `{start}-{end}`\n"
        f"- Retrieval map: `planning/manifests/closing_price_scene_retrieval_map.json`\n"
        f"- Boundary: `{scene['boundary_start_kind']} -> {scene['boundary_end_kind']}`\n"
        f"- Scene text SHA256: `{scene['scene_text_sha256']}`\n\n"
        "```fountain\n"
        f"{excerpt}\n"
        "```\n"
    )


def prompt_brief_text(scene_id: str) -> str:
    return (
        f"# {scene_id} Prompt Brief\n\n"
        f"- Scene ID: `{scene_id}`\n"
        "- Title: `TBD`\n"
        "- Dramatic function: `TBD`\n"
        "- Source excerpt: [scene_excerpt.md](scene_excerpt.md)\n"
        "- Retrieval map: `planning/manifests/closing_price_scene_retrieval_map.json`\n\n"
        "## Translation Notes\n\n"
        "- Replace this stub after scene-card enrichment.\n"
        "- Keep prompt language aligned with the canonical scene excerpt.\n"
    )


def review_notes_text(scene_id: str) -> str:
    return (
        f"# {scene_id} Review Notes\n\n"
        "Scaffold generated by `scripts/seed_scene_cards.py`.\n"
        "Add scene-specific review notes, approvals, or change requests here.\n"
    )


def infer_sequence_id(scene: dict[str, Any]) -> str:
    return f"SEQ{((scene['ordinal'] - 1) // 5) + 1:02d}"


def infer_phase_id(scene: dict[str, Any], scene_count: int) -> str:
    phases = [
        "PH_EQUILIBRIUM",
        "PH_CONFRONTATION",
        "PH_INVERSION",
        "PH_CRUCIBLE",
        "PH_RESOLUTION",
    ]
    bucket_size = max(1, scene_count // len(phases))
    phase_index = min((scene["ordinal"] - 1) // bucket_size, len(phases) - 1)
    return phases[phase_index]


def scene_card_text(scene: dict[str, Any], scene_count: int) -> str:
    ordinal = scene["ordinal"]
    prior_scenes = [] if ordinal == 1 else [f"SC{ordinal - 1:04d}"]
    next_expected_links = [] if ordinal == scene_count else [f"SC{ordinal + 1:04d}"]

    lines = [
        f"scene_id: {scene['scene_id']}",
        f"sequence_id: {infer_sequence_id(scene)}",
        f"phase_id: {infer_phase_id(scene, scene_count)}",
        f"title: \"TBD title for {scene['scene_id']}\"",
        "purpose: \"Placeholder scaffold seeded from the retrieval map; replace with canonical scene purpose.\"",
        "dramatic_function: \"TBD dramatic function derived during scene-card enrichment.\"",
        "location_id: LOC001",
        "time_of_day: UNKNOWN",
        "weather: \"TBD\"",
        "characters_present:",
        "  - C01",
        "primary_pov_character: C01",
        "continuity_refs:",
        "  wardrobe: []",
        "  props: []",
        f"  prior_scenes: {prior_scenes}",
        f"  next_expected_links: {next_expected_links}",
        "  time_continuity_note: \"TBD continuity note.\"",
        "visual_targets:",
        "  palette: \"TBD visual palette\"",
        "  lens_bias: \"TBD lens bias\"",
        "  framing_bias: \"TBD framing bias\"",
        "  movement_bias: \"TBD movement bias\"",
        "  lighting_bias: \"TBD lighting bias\"",
        "promptability_score: 3",
        "screen_excerpt_ref: scene_excerpt.md",
        "prompt_brief_ref: prompt_brief.md",
        "review_notes_ref: review_notes.md",
        "status: draft",
        "review_status: pending",
        "canon_lock: false",
    ]
    return "\n".join(lines) + "\n"


def write_if_missing(path: Path, content: str) -> bool:
    if path.exists():
        return False
    path.write_text(content, encoding="utf-8")
    return True


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def seed_scene_cards(
    source_path: Path,
    retrieval_map_path: Path,
    scenes_root: Path,
) -> int:
    map_data = load_json(retrieval_map_path)
    source_lines = read_source_lines(source_path)
    scenes = map_data["scenes"]
    scene_count = len(scenes)

    created_scene_dirs = 0
    created_scene_cards = 0
    created_prompt_briefs = 0
    created_review_notes = 0
    refreshed_excerpts = 0

    for scene in scenes:
        scene_dir = scenes_root / scene["scene_id"]
        if not scene_dir.exists():
            scene_dir.mkdir(parents=True, exist_ok=True)
            created_scene_dirs += 1

        excerpt_path = scene_dir / "scene_excerpt.md"
        excerpt_content = scene_excerpt_text(scene, map_data, source_lines)
        if write_if_changed(excerpt_path, excerpt_content):
            refreshed_excerpts += 1

        card_path = scene_dir / "scene_card.yaml"
        if write_if_missing(card_path, scene_card_text(scene, scene_count)):
            created_scene_cards += 1

        prompt_path = scene_dir / "prompt_brief.md"
        if write_if_missing(prompt_path, prompt_brief_text(scene["scene_id"])):
            created_prompt_briefs += 1

        review_notes_path = scene_dir / "review_notes.md"
        if write_if_missing(review_notes_path, review_notes_text(scene["scene_id"])):
            created_review_notes += 1

    print(
        "Scene scaffold seeded:",
        f"{scene_count} scenes total,",
        f"{created_scene_dirs} directories created,",
        f"{created_scene_cards} scene cards created,",
        f"{created_prompt_briefs} prompt briefs created,",
        f"{created_review_notes} review notes created,",
        f"{refreshed_excerpts} excerpts refreshed",
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        default="source/screenplay/closing_price.fountain",
        help="Path to the canonical Fountain screenplay used for excerpt extraction.",
    )
    parser.add_argument(
        "--retrieval-map",
        default="planning/manifests/closing_price_scene_retrieval_map.json",
        help="Path to the authoritative scene spine retrieval map.",
    )
    parser.add_argument(
        "--scenes-root",
        default="planning/scenes",
        help="Directory where SCxxxx scene folders should be created.",
    )
    args = parser.parse_args()

    return seed_scene_cards(
        source_path=Path(args.source),
        retrieval_map_path=Path(args.retrieval_map),
        scenes_root=Path(args.scenes_root),
    )


if __name__ == "__main__":
    raise SystemExit(main())
